name: homebrew
on:
  push:
    tags: 'v*'

jobs:
  main:
    name: Homebrew Bump
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: üç∫ Bump Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v2.0
        with:
          formula-name: spaceship
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_TOKEN }}
